/**
 * RealPro | Config Exports
 * © 2024-2025 Realpro SA. Tous droits réservés.
 */

export { env, isDev, isProd, isTest } from './env';
export {
  PROJECT_STATUSES,
  PROJECT_STATUS_LABELS,
  PROJECT_STATUS_COLORS,
  LOT_STATUSES,
  LOT_STATUS_LABELS,
  LOT_STATUS_COLORS,
  LOT_TYPES,
  LOT_TYPE_LABELS,
  USER_ROLES,
  ROLE_LABELS,
  ROLE_COLORS,
  LANGUAGES,
  LANGUAGE_LABELS,
  SUBSCRIPTION_STATUSES,
  SWISS_CANTONS,
  DEFAULT_PAGE_SIZE,
  PAGE_SIZE_OPTIONS,
  TRIAL_DAYS,
} from './constants';
